// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Message string `json:"message"`
}

type DynamicQueryRequest struct {
	Offset     int    `form:"offset,optional"`
	Limit      int    `form:"limit,optional"`
	OrderBy    string `form:"orderby,optional"`
	Asc        int    `form:"asc,optional"`
	FuzzyQuery bool   `form:"fuzzyQuery,default=true"`
	TableName  string `path:"table"`
}

type DynamicQueryResponse struct {
	Total int                      `json:"total"`
	Rows  []map[string]interface{} `json:"rows"`
}

type DynamicInsertOneRequest struct {
	TableName string `path:"table"`
}

type DynamicInsertOneResponse struct {
	Message string `json:"message"`
}

type DynamicUpdateRequest struct {
	TableName string `path:"table"`
}

type DynamicUpdateResponse struct {
	Message string `json:"message"`
}

type DynamicDeleteByQueryRequest struct {
	FuzzyQuery     bool                   `form:"fuzzyQuery,optional"`
	TableName      string                 `path:"table"`
	QueryCondition map[string]interface{} `json:"condition"`
}

type DynamicDeleteByQueryIdsRequest struct {
	TableName string `path:"table"`
	Ids       []int  `json:"ids"`
}

type DynamicDeleteResponse struct {
	Message      string `json:"message"`
	AffectedRows int    `json:"affectedRows"`
}
