// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"console-api/console/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/:module/:table/query",
				Handler: dynamicQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/:module/:table/add",
				Handler: dynamicInsertOneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/:module/:table/update",
				Handler: dynamicUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/:module/:table/deleteByQuery",
				Handler: dynamicDeleteByQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/:module/:table/deleteByIds",
				Handler: dynamicDeleteByIdsHandler(serverCtx),
			},
		},
	)
}
